#ifndef XSLFORMAT_H
#define XSLFORMAT_H
#include <iostream>

/*
修改说明:

2017年12月15日 邹书强 V1.03
1、增加了tuner模式测试
2、整理了多处编译警告
3、调整了多tuner情况下demux的管理
4、增加了性能测试和FLASH拷机测试

2018年1月11日 邹书强 V1.04
1、修改了tuner模块测试下，env环境被修改后未及时更新的问题
2、完善了自动测试演示FOR_AUTO_RUN和纯命令运行模式ENABLE_TESTCASE，进一步减少了ENABLE_TESTCASE==0时的gtest lib体积
*/

const char* bufferXsl = 
//"<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?> \n"

"<?xml version=\"1.0\" encoding=\"GB2312\"?> \n"
"<xsl:stylesheet version=\"1.0\" \n"
"xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\"> \n"
"  \n"
"<xsl:template match=\"/\"> \n"
"  <html> \n"
"  <body> \n"
"  <h2 align=\"center\">长虹网络公司CHDRV测试报告(V1.04)</h2>  \n"
"  <xsl:apply-templates select=\"testsuites/testhead\"/>  \n"
"  <xsl:apply-templates select=\"testsuites\"/>  \n"
"  </body> \n"
"  </html> \n"
"</xsl:template> \n"
" \n"
" <xsl:template match=\"testsuites/testhead\"> \n"
"    <table border=\"1\" width=\"100%%\"> \n"
"    <tr> \n"
"      <td bgcolor=\"#9acd32\">Project Name</td> \n"
"      <td><xsl:value-of select=\"@name\"/></td> \n"
"    </tr> \n"
"    <tr> \n"
"      <td bgcolor=\"#9acd32\">Build Path</td> \n"
"      <td><xsl:value-of select=\"@path\"/></td> \n"
"    </tr> \n"
"    <tr> \n"
"      <td bgcolor=\"#9acd32\">Build Date</td> \n"
"      <td><xsl:value-of select=\"@date\"/></td> \n"
"    </tr> \n"
"	<tr> \n"
"      <td bgcolor=\"#9acd32\">Tester</td> \n"
"      <td><xsl:value-of select=\"@tester\"/></td> \n"
"    </tr>\n"
"     </table>\n"
"	  <br/> \n"
"</xsl:template> \n" 
" \n"
"<xsl:template match=\"testsuites\"> \n"
"    <table border=\"1\" width=\"100%%\"> \n"
"    <tr bgcolor=\"#9acd32\"> \n"
"      <th align=\"left\">module</th> \n"
"      <th align=\"left\">tests</th> \n"
"      <th align=\"left\">time</th> \n"
"      <th align=\"left\">failed</th> \n"
"    </tr> \n"
" \n"
"    	<xsl:choose> \n"
"        <xsl:when test=\"@failures &gt; 0\"> \n"
"          <tr bgcolor=\"#ff0000\"> \n"
"          <td><xsl:value-of select=\"@name\"/></td> \n"
"		      <td><xsl:value-of select=\"@tests\"/></td> \n"
"		      <td><xsl:value-of select=\"@time\"/></td> \n"
"		      <td><xsl:value-of select=\"@failures\"/></td>   \n"  
"		      </tr> \n"
"        </xsl:when> \n"
"        <xsl:otherwise> \n"
"          <tr> \n"
"          <td><xsl:value-of select=\"@name\"/></td> \n"
"		      <td><xsl:value-of select=\"@tests\"/></td> \n"
"		      <td><xsl:value-of select=\"@time\"/></td> \n"
"		      <td><xsl:value-of select=\"@failures\"/></td>     \n"
"		      </tr>            	 \n"
"        </xsl:otherwise> \n"
"      </xsl:choose>       \n"
" \n"
"    </table> \n"
"    <br/> \n"
"     \n"
"    <xsl:apply-templates select=\"testsuite\"/> \n"
" \n"
"    <br/><p></p> \n"
"    <h2 align=\"center\">failed test case</h2> \n"
"    <table border=\"1\"  width=\"100%%\"> \n"
"    <tr bgcolor=\"red\"> \n"
"    	<th align=\"left\">module name</th> \n"
"      <th align=\"left\">case name</th> \n"
"      <th align=\"left\">description</th> \n"
"      <th align=\"left\">message</th> \n"
"    </tr> \n"
"      <xsl:apply-templates select=\"testsuite/testcase/failure\"/> \n"
"    </table> \n"
"</xsl:template> \n"
"\n"
"<xsl:template match=\"testsuite\"> \n"
"    <h2><xsl:value-of select=\"@name\"/></h2> \n"
"    <table border=\"1\"  width=\"100%%\"> \n"
"    <tr bgcolor=\"#9acd32\"> \n"
"      <th align=\"left\">module</th> \n"
"      <th align=\"left\">tests</th> \n"
"      <th align=\"left\">time</th> \n"
"      <th align=\"left\">failed</th> \n"
"    </tr> \n"
"    	<xsl:choose> \n"
"        <xsl:when test=\"@failures &gt; 0\"> \n"
"          <tr bgcolor=\"#ff0000\"> \n"
"          <td><xsl:value-of select=\"@name\"/></td> \n"
"		      <td><xsl:value-of select=\"@tests\"/></td> \n"
"		      <td><xsl:value-of select=\"@time\"/></td> \n"
"		      <td><xsl:value-of select=\"@failures\"/></td>   \n"  
"		      </tr> \n"
"        </xsl:when> \n"
"        <xsl:otherwise> \n"
"          <tr> \n"
"          <td><xsl:value-of select=\"@name\"/></td> \n"
"		      <td><xsl:value-of select=\"@tests\"/></td> \n"
"		      <td><xsl:value-of select=\"@time\"/></td> \n"
"		      <td><xsl:value-of select=\"@failures\"/></td>     \n"
"		      </tr>            	 \n"
"        </xsl:otherwise> \n"
"      </xsl:choose>       \n"
" \n"
"	  <br>\n"
"	  </br>\n"
"	<tr bgcolor=\"#cafda2\">\n"
"	<th align=\"left\">case name</th>\n"
"      <th align=\"left\">description</th>\n"
"      <th align=\"left\">time</th>\n"
"      <th align=\"left\">result</th>\n"
"	</tr>\n"
"	<xsl:for-each select=\"testcase\">\n"
"     <tr align=\"left\">\n"
"      <td><xsl:value-of select=\"@name\"/></td>\n"
"      <td><xsl:value-of select=\"@description\"/></td>\n"
"      <td><xsl:value-of select=\"@time\"/></td>\n"
"	<xsl:choose>\n"
"        <xsl:when test=\"failure\">\n"
"	  <td bgcolor=\"ff0000\">FAIL</td>\n"
"	  </xsl:when>\n"
"	  <xsl:otherwise>\n"
"	  <td bgcolor=\"00ff00\">OK</td>\n"
"	  </xsl:otherwise>\n"
"	  </xsl:choose>\n"
"    </tr>\n"
"	</xsl:for-each>\n"
"    </table> \n"
"</xsl:template> \n"
" \n"
" \n"
"<xsl:template match=\"testcase\"> \n"
"    <tr> \n"
"      <td><xsl:value-of select=\"@name\"/></td> \n"
"      <td><xsl:value-of select=\"../@name\"/></td> \n"
"      <td><xsl:value-of select=\"failure/@message\"/></td>    \n" 
"    </tr> \n"
"</xsl:template> \n"
" \n"
"<xsl:template match=\"failure\"> \n"
"    <tr> \n"
"    	<td><xsl:value-of select=\"../../@name\"/></td> \n"
"      <td><xsl:value-of select=\"../@name\"/></td> \n"
"      <td><xsl:value-of select=\"../@description\"/></td>\n"
//"      <td><xsl:value-of select=\"@message\"/><br/> <xsl:value-of select=\".\"/></td> \n"
"      <td><xsl:value-of select=\".\" disable-output-escaping=\"yes\"/></td> \n"
"    </tr> \n"
"</xsl:template> \n"
" \n"
"</xsl:stylesheet>\n";


#endif //XSLFORMAT_H
